name: flutter_book
description: 《Flutter实战》

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # 新添加的依赖
  english_words: ^3.1.3
  # flutter_screenutil: ^0.6.0
  flutter_easyrefresh: ^1.2.7
  flutter_swiper: ^1.1.6
  # carousel_slider: ^1.3.0
  # cached_network_image: ^0.8.0
  dio: ^2.0.2
  json_serializable: ^2.0.0
  fluttertoast: ^3.1.3
  #  flutter_webview_plugin: ^0.3.0+2
  flutter_html: ^0.9.4
  url_launcher: ^5.0.2
  objectdb: ^1.0.5
  #  flutter_redux: ^0.5.2
  connectivity: ^0.3.2
  package_info: ^0.4.0+1
  extended_image: ^0.6.3
  shared_preferences: ^0.5.4+1
  flustars: ^0.2.6+1
  event_bus: 1.1.0
  provider: ^3.1.0+1
  sqflite: ^1.1.7+1
  flutter_picker: ^1.1.0
  image_picker: ^0.6.1+10
  flutter_spinkit: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # assets-generator-begin
    # assets/imgs/*
    - assets/imgs/
    - assets/imgs/actionbar_checkin.png
    - assets/imgs/actionbar_search.png
    - assets/imgs/aliuser_title_back_normal.png
    - assets/imgs/arrow_right.png
    - assets/imgs/bookshelf_add.png
    - assets/imgs/bookshelf_bg.png
    - assets/imgs/bookshelf_cloud_0.png
    - assets/imgs/bookshelf_cloud_1.png
    - assets/imgs/bookshelf_cloud_2.png
    - assets/imgs/bookshelf_cloud_3.png
    - assets/imgs/bookshelf_continue_read.png
    - assets/imgs/detail_chapter.png
    - assets/imgs/detail_down.png
    - assets/imgs/detail_fold_bg.png
    - assets/imgs/detail_latest.png
    - assets/imgs/detail_star.png
    - assets/imgs/detail_star_half.png
    - assets/imgs/detail_up.png
    - assets/imgs/detail_write_comment.png
    - assets/imgs/home_search.png
    - assets/imgs/home_tip.png
    - assets/imgs/icon.png
    - assets/imgs/icon_avatar.png
    - assets/imgs/icon_inputPhoneNum.png
    - assets/imgs/icon_inputPwd.png
    - assets/imgs/icon_menu_catalog.png
    - assets/imgs/icon_menu_share.png
    - assets/imgs/icon_user_avatar.png
    - assets/imgs/img_meizi.jpg
    - assets/imgs/me_action.png
    - assets/imgs/me_buy.png
    - assets/imgs/me_comment.png
    - assets/imgs/me_coupon.png
    - assets/imgs/me_date.png
    - assets/imgs/me_favorite.png
    - assets/imgs/me_feedback.png
    - assets/imgs/me_gift.png
    - assets/imgs/me_night.png
    - assets/imgs/me_record.png
    - assets/imgs/me_setting.png
    - assets/imgs/me_theme.png
    - assets/imgs/me_vip.png
    - assets/imgs/me_wallet.png
    - assets/imgs/menu_category.png
    - assets/imgs/menu_complete.png
    - assets/imgs/menu_publish.png
    - assets/imgs/menu_rank.png
    - assets/imgs/menu_vip.png
    - assets/imgs/placeholder_avatar.png
    - assets/imgs/pub_back_gray.png
    - assets/imgs/pub_back_white.png
    - assets/imgs/read_bg.png
    - assets/imgs/read_icon_brightness.png
    - assets/imgs/read_icon_catalog.png
    - assets/imgs/read_icon_chapter_next.png
    - assets/imgs/read_icon_chapter_previous.png
    - assets/imgs/read_icon_font.png
    - assets/imgs/read_icon_more.png
    - assets/imgs/read_icon_setting.png
    - assets/imgs/read_icon_vip.png
    - assets/imgs/read_icon_voice.png
    - assets/imgs/read_more_detail.png
    - assets/imgs/reader_battery.png
    - assets/imgs/tab_bookshelf_n.png
    - assets/imgs/tab_bookshelf_p.png
    - assets/imgs/tab_bookstore_n.png
    - assets/imgs/tab_bookstore_p.png
    - assets/imgs/tab_me_n.png
    - assets/imgs/tab_me_p.png
    - assets/imgs/tab_writer_n.png
    - assets/imgs/tab_writer_p.png
    # assets-generator-end
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
